services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npx nodemon server.js

  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    command: npm run dev

  database:
      build: ./database
      env_file:
        - ./database/.env
      ports:
        - "3306:3306"


